# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_substring <- function(pattern, x) {
    .Call('_bfstr_count_substring', PACKAGE = 'bfstr', pattern, x)
}

string_replace <- function(pattern, replacement, x) {
    .Call('_bfstr_string_replace', PACKAGE = 'bfstr', pattern, replacement, x)
}

string_table <- function(x) {
    .Call('_bfstr_string_table', PACKAGE = 'bfstr', x)
}

